import os
from dotenv import load_dotenv

load_dotenv()

POSTGRESQL_DATABASE_URL=os.getenv("POSTGRESQL_DATABASE_URL")
JWT_SECRET_KEY=os.getenv("JWT_SECRET_KEY")
JWT_ALGORITHM=os.getenv("JWT_ALGORITHM", "HS256")
JWT_EXPIRATION=int(os.getenv("JWT_EXPIRATION", 600))
ACCESS_TOKEN_EXPIRE_MINUTES=int(os.getenv("ACCESS_TOKEN_EXPIRE_MINUTES", 30))